#pragma once
#include"base.h"
#include"Texture.h"
/// <summary>
/// アルファベットと数字のテクスチャ
/// </summary>
class CharacterTexture
{
public:
	CharacterTexture()
	{
		texture0yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/0.png");
		texture1yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/1.png");
		texture2yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/2.png");
		texture3yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/3.png");
		texture4yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/4.png");
		texture5yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/5.png");
		texture6yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/6.png");
		texture7yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/7.png");
		texture8yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/8.png");
		texture9yellow = new Texture("res/texture/alphabet&numbers/numbersyellow/9.png");
		textureColonyellow = new Texture("res/texture/alphabet&numbers/numbersyellow/colon.png");
		texturePointyellow = new Texture("res/texture/alphabet&numbers/numbersyellow/point.png");
		textureAyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/A.png");
		textureByellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/B.png");
		textureCyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/C.png");
		textureDyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/D.png");
		textureEyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/E.png");
		textureFyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/F.png");
		textureGyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/G.png");
		textureHyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/H.png");
		textureIyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/I.png");
		textureJyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/J.png");
		textureKyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/K.png");
		textureLyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/L.png");
		textureMyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/M.png");
		textureNyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/N.png");
		textureOyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/O.png");
		texturePyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/P.png");
		textureQyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/Q.png");
		textureRyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/R.png");
		textureSyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/S.png");
		textureTyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/T.png");
		textureUyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/U.png");
		textureVyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/V.png");
		textureWyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/W.png");
		textureXyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/X.png");
		textureYyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/Y.png");
		textureZyellow = new Texture("res/texture/alphabet&numbers/alphabetyellow/Z.png");

		texture0white = new Texture("res/texture/alphabet&numbers/numberswhite/0.png");
		texture1white = new Texture("res/texture/alphabet&numbers/numberswhite/1.png");
		texture2white = new Texture("res/texture/alphabet&numbers/numberswhite/2.png");
		texture3white = new Texture("res/texture/alphabet&numbers/numberswhite/3.png");
		texture4white = new Texture("res/texture/alphabet&numbers/numberswhite/4.png");
		texture5white = new Texture("res/texture/alphabet&numbers/numberswhite/5.png");
		texture6white = new Texture("res/texture/alphabet&numbers/numberswhite/6.png");
		texture7white = new Texture("res/texture/alphabet&numbers/numberswhite/7.png");
		texture8white = new Texture("res/texture/alphabet&numbers/numberswhite/8.png");
		texture9white = new Texture("res/texture/alphabet&numbers/numberswhite/9.png");
		textureColonwhite = new Texture("res/texture/alphabet&numbers/numberswhite/colon.png");
		texturePointwhite = new Texture("res/texture/alphabet&numbers/numberswhite/point.png");
		textureAwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/A.png");
		textureBwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/B.png");
		textureCwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/C.png");
		textureDwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/D.png");
		textureEwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/E.png");
		textureFwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/F.png");
		textureGwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/G.png");
		textureHwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/H.png");
		textureIwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/I.png");
		textureJwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/J.png");
		textureKwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/K.png");
		textureLwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/L.png");
		textureMwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/M.png");
		textureNwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/N.png");
		textureOwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/O.png");
		texturePwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/P.png");
		textureQwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/Q.png");
		textureRwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/R.png");
		textureSwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/S.png");
		textureTwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/T.png");
		textureUwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/U.png");
		textureVwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/V.png");
		textureWwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/W.png");
		textureXwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/X.png");
		textureYwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/Y.png");
		textureZwhite = new Texture("res/texture/alphabet&numbers/alphabetwhite/Z.png");
	}
	~CharacterTexture()
	{
		delete texture0yellow;
		delete texture1yellow;
		delete texture2yellow;
		delete texture3yellow;
		delete texture4yellow;
		delete texture5yellow;
		delete texture6yellow;
		delete texture7yellow;
		delete texture8yellow;
		delete texture9yellow;
		delete textureColonyellow;
		delete texturePointyellow;
		delete textureAyellow;
		delete textureByellow;
		delete textureCyellow;
		delete textureDyellow;
		delete textureEyellow;
		delete textureFyellow;
		delete textureGyellow;
		delete textureHyellow;
		delete textureIyellow;
		delete textureJyellow;
		delete textureKyellow;
		delete textureLyellow;
		delete textureMyellow;
		delete textureNyellow;
		delete textureOyellow;
		delete texturePyellow;
		delete textureQyellow;
		delete textureRyellow;
		delete textureSyellow;
		delete textureTyellow;
		delete textureUyellow;
		delete textureVyellow;
		delete textureWyellow;
		delete textureXyellow;
		delete textureYyellow;
		delete textureZyellow;

		delete texture0white;
		delete texture1white;
		delete texture2white;
		delete texture3white;
		delete texture4white;
		delete texture5white;
		delete texture6white;
		delete texture7white;
		delete texture8white;
		delete texture9white;
		delete textureColonwhite;
		delete texturePointwhite;
		delete textureAwhite;
		delete textureBwhite;
		delete textureCwhite;
		delete textureDwhite;
		delete textureEwhite;
		delete textureFwhite;
		delete textureGwhite;
		delete textureHwhite;
		delete textureIwhite;
		delete textureJwhite;
		delete textureKwhite;
		delete textureLwhite;
		delete textureMwhite;
		delete textureNwhite;
		delete textureOwhite;
		delete texturePwhite;
		delete textureQwhite;
		delete textureRwhite;
		delete textureSwhite;
		delete textureTwhite;
		delete textureUwhite;
		delete textureVwhite;
		delete textureWwhite;
		delete textureXwhite;
		delete textureYwhite;
		delete textureZwhite;
	}

public:
	Texture* texture0yellow;
	Texture* texture1yellow;
	Texture* texture2yellow;
	Texture* texture3yellow;
	Texture* texture4yellow;
	Texture* texture5yellow;
	Texture* texture6yellow;
	Texture* texture7yellow;
	Texture* texture8yellow;
	Texture* texture9yellow;
	Texture* textureColonyellow;
	Texture* texturePointyellow;
	Texture* textureAyellow;
	Texture* textureByellow;
	Texture* textureCyellow;
	Texture* textureDyellow;
	Texture* textureEyellow;
	Texture* textureFyellow;
	Texture* textureGyellow;
	Texture* textureHyellow;
	Texture* textureIyellow;
	Texture* textureJyellow;
	Texture* textureKyellow;
	Texture* textureLyellow;
	Texture* textureMyellow;
	Texture* textureNyellow;
	Texture* textureOyellow;
	Texture* texturePyellow;
	Texture* textureQyellow;
	Texture* textureRyellow;
	Texture* textureSyellow;
	Texture* textureTyellow;
	Texture* textureUyellow;
	Texture* textureVyellow;
	Texture* textureWyellow;
	Texture* textureXyellow;
	Texture* textureYyellow;
	Texture* textureZyellow;

	Texture* texture0white;
	Texture* texture1white;
	Texture* texture2white;
	Texture* texture3white;
	Texture* texture4white;
	Texture* texture5white;
	Texture* texture6white;
	Texture* texture7white;
	Texture* texture8white;
	Texture* texture9white;
	Texture* textureColonwhite;
	Texture* texturePointwhite;
	Texture* textureAwhite;
	Texture* textureBwhite;
	Texture* textureCwhite;
	Texture* textureDwhite;
	Texture* textureEwhite;
	Texture* textureFwhite;
	Texture* textureGwhite;
	Texture* textureHwhite;
	Texture* textureIwhite;
	Texture* textureJwhite;
	Texture* textureKwhite;
	Texture* textureLwhite;
	Texture* textureMwhite;
	Texture* textureNwhite;
	Texture* textureOwhite;
	Texture* texturePwhite;
	Texture* textureQwhite;
	Texture* textureRwhite;
	Texture* textureSwhite;
	Texture* textureTwhite;
	Texture* textureUwhite;
	Texture* textureVwhite;
	Texture* textureWwhite;
	Texture* textureXwhite;
	Texture* textureYwhite;
	Texture* textureZwhite;
};